on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build_wheels:
    runs-on: "${{ matrix.os == 'wasm' && 'ubuntu-latest' || matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["wasm"] # TODO (fail with missing symbols on native): ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14
    steps:
      - uses: "actions/checkout@v4"
      
      - uses: "actions/cache@v4"
        id: "cache"
        with:
          path: |
            ./build
            !./build/*/_deps/*-src
            ~/.cache/ccache
          key: "${{ matrix.os }}-cibuildwheel-${{ hashFiles('CMakeLists.txt', '*.cmake', 'pyproject.toml') }}"
          restore-keys: "${{ matrix.os }}-cibuildwheel-"
      
      - uses: "pypa/cibuildwheel@v3.0.0b5"
        env:
          CIBW_PLATFORM: "${{ matrix.os == 'wasm' && 'pyodide' || 'auto' }}"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "cibw-wheels-${{ matrix.os }}"
          path: "./wheelhouse/*.whl"

      - if: "always()"  # Always run this step, even if previous ones fail
        uses: "actions/upload-artifact@v4"
        with:
          name: "cache-${{ matrix.os }}"
          path: |
            ./build
            !./build/*/_deps/*-src
            ~/.cache/ccache
          
      - if: "failure()" # Save cache even on failures
        uses: "actions/cache/save@v4"
        with:
          key: "${{ steps.cache-prime-numbers-restore.outputs.cache-primary-key }}"
          path: |
            ./build
            !./build/*/_deps/*-src
            ~/.cache/ccache
          
  deploy_wheels_to_pages: # keeping old ones
    needs: "build_wheels"
    if: "github.ref == 'refs/heads/master'"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "gh-pages"
      
      - uses: "actions/download-artifact@v4"
        with:
          path: "__artifacts"
          
      - name: "Copy new wheels into registry and rebuild index"
        run: |
          find __artifacts -name '*.whl' -exec cp {} . \; # Overwrites matching versions
          rm -rf __artifacts
          
          # Create PEP 503 simple index (with only one package at root index.html)
          echo "<!DOCTYPE html><html><head><title>OCP wasm registry</title></head><body><h1>OCP wasm PEP503 registry</h1>" >index.html
          for whl in *.whl; do
            echo "<a href=\"$whl\">$whl</a><br/>" >>index.html
          done
          echo "</body></html>" >>index.html

      - name: "Commit and push"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -v .
          git commit -m "Update wheel registry" || echo "No changes to commit"
          git push origin gh-pages


  # TODO: deploy_wheels_to_pypi: (doesn't support webassembly)
