on: ["push", "pull_request"]

jobs:
  build_wheels:
    runs-on: "${{ matrix.os == 'wasm' && 'ubuntu-latest' || matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["wasm"] # TODO: ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14

    steps:
      - uses: "actions/checkout@v4"

      - uses: "pypa/cibuildwheel@v3.0.0b4" # Beta version supports newer pyodide
        env:
          CIBW_PLATFORM: "${{ matrix.os == 'wasm' && 'pyodide' || 'auto' }}"
          # TODO: Build multiple pyodide versions (stable and latest)

      - uses: "actions/upload-artifact@v4"
        with:
          #name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: "./wheelhouse/*.whl"
