on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build_wheels:
    runs-on: "${{ matrix.os == 'wasm' && 'ubuntu-latest' || matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["wasm"] # TODO (fail with missing symbols on native): ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14
        build_type: ["Release"] # FIXME: "Debug" builds not working for now due to wasm validation failures
    steps:
      - uses: "actions/checkout@v4"
      
      - uses: "actions/cache@v4"
        id: "cache"
        with:
          path: |
            build
            ~/.cache
          key: "${{ matrix.os }}-${{ matrix.build_type }}-cibuildwheel-${{ github.ref_name }}-${{ hashFiles('CMakeLists.txt', '*.cmake', 'pyproject.toml', '*.py') }}"
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.build_type }}-cibuildwheel-${{ github.ref_name }}-
            ${{ matrix.os }}-${{ matrix.build_type }}-cibuildwheel-master-
            ${{ matrix.os }}-${{ matrix.build_type }}-cibuildwheel-
      
      - uses: "pypa/cibuildwheel@v3.0.0b5"
        env:
          CIBW_PLATFORM: "${{ matrix.os == 'wasm' && 'pyodide' || 'auto' }}"
          SKBUILD_CMAKE_BUILD_TYPE: "${{ matrix.build_type }}"
          SKBUILD_BUILD_TOOL_ARGS: "-d;explain" # Useful to debug if caches are not working as expected

      - uses: "actions/upload-artifact@v4"
        with:
          name: "cibw-wheels-${{ matrix.os }}-${{ matrix.build_type }}"
          path: "wheelhouse/*.whl"

      - if: "always()"  # Always run this step, even if previous ones fail
        uses: "actions/upload-artifact@v4"
        with:
          name: "cache-${{ matrix.os }}-${{ matrix.build_type }}"
          path: |
            build
            ~/.cache
          
      - if: "failure()" # Save cache even on failures
        uses: "actions/cache/save@v4"
        with:
          key: "${{ steps.cache-prime-numbers-restore.outputs.cache-primary-key }}"
          path: |
            build
            ~/.cache
          
  deploy_wheels_to_pages: # keeping old ones
    needs: "build_wheels"
    if: "github.ref == 'refs/heads/master'"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "gh-pages"
      
      - uses: "actions/download-artifact@v4"  # Overwrites matching versions
        with:
          path: "."
          
      - name: "Rebuild index of registry"
        run: |
          echo "<!DOCTYPE html><html><head><title>OCP wasm registry</title></head><body><h1>OCP wasm PEP503 registry</h1>" >index.html
          find . -type f -name "*.whl" | sort -u | while read -r file; do
            echo "<a href=\"${file#./}\">${file#./}</a>" >>index.html
          done
          echo "</body></html>" >>index.html

      - name: "Commit and push"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -v .
          git commit -m "Update wheel registry" || echo "No changes to commit"
          git push origin gh-pages


  # TODO: deploy_wheels_to_pypi: (doesn't support webassembly)
