on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build_wheels:
    runs-on: "${{ matrix.os == 'wasm' && 'ubuntu-latest' || matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["wasm", "ubuntu-latest"] # TODO: ubuntu-24.04-arm, windows-latest, macos-13, macos-14
        include:
          - os: "wasm"
            cibw-build: "cp313-*"
    steps:
      - uses: "actions/checkout@v4"

      - uses: "yeicor/cibuildwheel@v3.1.0"
        env:
          CIBW_PLATFORM: "${{ matrix.os == 'wasm' && 'pyodide' || 'auto' }}"
          CIBW_BUILD: "${{ matrix.cibw-build && matrix.cibw-build || '*' }}"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "cibw-wheels-${{ matrix.os }}"
          path: "./wheelhouse/*.whl"
          
  deploy_wheels_to_pages: # keeping old ones
    needs: "build_wheels"
    if: "github.ref == 'refs/heads/master'"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "gh-pages"
          path: "gh-pages"
          fetch-depth: 0

      - uses: "actions/download-artifact@v4"
        with:
          path: "gh-pages"

      - run: | # Add a simple index.html listing all wheels
          cd gh-pages
          cat << 'EOF' > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Wheels</title>
          <style>
            body {
              font-family: system-ui, sans-serif;
              background: #fdfdfd;
              color: #222;
              padding: 2rem;
              max-width: 720px;
              margin: auto;
            }
            h1 {
              font-size: 1.5rem;
              margin-bottom: 1rem;
            }
            a {
              display: block;
              padding: 0.4rem 0.6rem;
              margin: 0.2rem 0;
              background: #f0f0f0;
              color: #0366d6;
              border-radius: 4px;
              text-decoration: none;
              font-family: monospace;
            }
            a:hover {
              background: #e6e6e6;
              text-decoration: underline;
            }
          </style>
          </head>
          <body>
          <h1>Wheels</h1>
          EOF

          for f in *.whl; do
            echo "  <a href=\"$f\">$f</a>" >> index.html
          done

          cat << 'EOF' >> index.html
          </body>
          </html>
          EOF

      - run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wasm
          git commit -m "Add new wasm wheels $(date -u +'%Y-%m-%d %H:%M:%S')" || true
          git push origin gh-pages


  # TODO: deploy_wheels_to_pypi: (doesn't support webassembly)
